#!/bin/sh
WIN=$(xdotool getactivewindow)

if [ -n "$WIN" ];
   then
       # xtitle -f "%s " | strcut
       xtitle $WIN
   else
       exit 0
   fi

case $BLOCK_BUTTON in
    1) i3-msg layout tabbed ;;
    2) i3-msg layout stacked ;;
    3) i3-msg layout toggle split ;;
    4) ;;
    5) ;;
esac
